### ISSUE TITLE
Some bdb implementations require only str keys

### ISSUE THREAD

**Issue by baverman** [baverman/snaked#17]
<pre>
Traceback (most recent call last):
File "/usr/local/lib/python2.6/dist-packages/snaked-0.3.7-py2.6.egg/snaked/core/plugins.py", line 122, in editor_closed
p.editor_closed(editor)
File "/usr/local/lib/python2.6/dist-packages/snaked-0.3.7-py2.6.egg/snaked/plugins/save_positions/__init__.py", line 27, in editor_closed
prefs[editor.uri] = str(editor.cursor.get_line())
File "/usr/local/lib/python2.6/dist-packages/snaked-0.3.7-py2.6.egg/snaked/core/prefs.py", line 85, in __setitem__
self.db[key] = value
File "/usr/lib/python2.6/bsddb/__init__.py", line 276, in __setitem__
_DeadlockWrap(wrapF) # self.db[key] = value
File "/usr/lib/python2.6/bsddb/dbutils.py", line 68, in DeadlockWrap
return function(*_args, **_kwargs)
File "/usr/lib/python2.6/bsddb/__init__.py", line 275, in wrapF
self.db[key] = value
TypeError: String or Integer object expected for key, unicode found
</pre>

**Comment by baverman** [comment]
fixed
