### ISSUE TITLE
Exception on extending smart selection at and of buffer

### ISSUE THREAD

**Issue by baverman** [baverman/snaked#2]
<pre>Traceback (most recent call last):
  File "/home/bobrov/work/snaked/snaked/core/shortcuts.py", line 109, in activate
    return cb(key, modifier, *(ctx + args))
  File "/home/bobrov/work/snaked/snaked/core/plugins.py", line 79, in activate_plugin_shortcut
    shortcut.callback(editor, *args)
  File "/home/bobrov/work/snaked/snaked/plugins/edit_and_select/__init__.py", line 18, in smart_select
    select_range(editor.buffer, *get_smart_select(editor))
  File "/home/bobrov/work/snaked/snaked/plugins/edit_and_select/smart_select.py", line 107, in get_smart_select
    return line_smart_extend(True, start, end)
  File "/home/bobrov/work/snaked/snaked/plugins/edit_and_select/smart_select.py", line 162, in line_smart_extend
    if not in_quotes and rchars[0] in (u'(', u'[', "'", '"'):
IndexError: string index out of range</pre>

**Comment by baverman** [comment]
fixed
