### ISSUE TITLE
bug: external tool / do not run, unicode issue

### ISSUE THREAD

**Issue by bibile** [baverman/snaked#21]
I added a PyFlakes tool, like in the documentation.
While running it (alt-x), I get that:

<pre>Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/snaked-0.4-py2.6.egg/snaked/core/shortcuts.py", line 109, in activate
    return cb(key, modifier, *(ctx + args))
  File "/usr/local/lib/python2.6/dist-packages/snaked-0.4-py2.6.egg/snaked/core/plugins.py", line 88, in activate_plugin_shortcut
    shortcut.callback(editor, *args)
  File "/usr/local/lib/python2.6/dist-packages/snaked-0.4-py2.6.egg/snaked/plugins/external_tools/__init__.py", line 70, in run_tool
    menu = get_run_menu(prefs, editor)
  File "/usr/local/lib/python2.6/dist-packages/snaked-0.4-py2.6.egg/snaked/plugins/external_tools/__init__.py", line 33, in get_run_menu
    to_str(prefs[tool]['langs'].split(','))):
TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'</pre>

**Comment by baverman** [comment]
Fixed in 0.4.2, please upgrade and check.

**Comment by bibile** [comment]
no idea if it works. now I get a error at startup.
I launch snaked from the terminal : snaked test.py
test.py is a simple python file.
I get:

<pre>Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/snaked-0.4.2-py2.6.egg/snaked/util/__init__.py", line 14, in idle_callback
    callable(*args, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/snaked-0.4.2-py2.6.egg/snaked/core/manager.py", line 107, in set_editor_prefs
    guesser = self.get_lang_guesser(root)
  File "/usr/local/lib/python2.6/dist-packages/snaked-0.4.2-py2.6.egg/snaked/core/manager.py", line 70, in get_lang_guesser
    contexts_filename = os.path.join(project_root, '.snaked_project', 'contexts')
  File "/usr/lib/python2.6/posixpath.py", line 67, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'</pre>

I hope I removed snaked-0.4 correctly.
I did :
easy_install -m snaked-0.4-py2.6.egg
rm -rf snaked-0.4-py2.6.egg
in /usr/local/lib/python2.6/dist-packages

**Comment by bibile** [comment]
do you know how to write the Traceback in this github issues_comments ?
it display poorly :/

**Comment by bibile** [comment]
with 0.43, I get back like before. things work well, can start, edit, enjoy, .. but I can not run extenal_tools (like pyflakes, as shown in the documentation)

**Comment by baverman** [comment]
> now I get a error at startup.

Sorry for that, this is my bad, there are new not well tested features in 0.4.2. Fixed in 0.4.3.

> I hope I removed snaked-0.4 correctly

As as rule, manual removing is not necessary.

> do you know how to write the Traceback

I use "pre" tags around traceback.
&lt;pre&gt;
insert traceback here
&lt;/pre&gt;

**Comment by bibile** [comment]
thanks for the < pre >, I will use it.
about external_tools, maybe I should say that I am using linux (last ubuntu, gnome..)
I have pyflakes.

**Comment by baverman** [comment]
> but I can not run extenal_tools 

Any tracebacks or other stdout? It runs well on my environment.

**Comment by bibile** [comment]
I open a simple file:

<pre>import time
print time.clock()</pre>

I get that, trying to run pyflakes command, like here http://packages.python.org/snaked/_images/external-tools.png :

<pre>Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/snaked-0.4.3-py2.6.egg/snaked/core/shortcuts.py", line 109, in activate
    return cb(key, modifier, *(ctx + args))
  File "/usr/local/lib/python2.6/dist-packages/snaked-0.4.3-py2.6.egg/snaked/core/plugins.py", line 98, in activate_plugin_shortcut
    shortcut.callback(editor, *args)
  File "/usr/local/lib/python2.6/dist-packages/snaked-0.4.3-py2.6.egg/snaked/plugins/external_tools/__init__.py", line 70, in run_tool
    menu = get_run_menu(prefs, editor)
  File "/usr/local/lib/python2.6/dist-packages/snaked-0.4.3-py2.6.egg/snaked/plugins/external_tools/__init__.py", line 33, in get_run_menu
    to_str(prefs[tool]['langs'].split(','))):
TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'</pre>

**Comment by baverman** [comment]
Wuf, I finally got it. Fixed in 0.4.4.

Very hard to trace problems when they are not reproduced. I appreciate your patience, you helped me much, thanks again.

**Comment by bibile** [comment]
perfect !
I could get my _Run command, with: python %f
thanks a lot ! great editor so far.
Do you think about making a package, . deb .... ?
maybe too early ?

**Comment by baverman** [comment]
> Do you think about making a package, . deb .... ?
> maybe too early ?

It's very early. Too much codebase changes now. New features, refactorings. Snaked need to be more stable to get packaged.

I think snaked's distribution via pypi should be easy enough for installing by python developers and allows me to do often releases.

**Comment by bibile** [comment]
ok. good enough like that.
when you will want to increase the number of users, you can make the .deb
but it's probably good to wait for a stable codebase.

another topic, maybe not really important, but I could not get snaked working under windows XP. no error message. I launch the .exe, and just get nothing.
that was with 0.4.
but maybe, it's better not to focus too many plateform now.

**Comment by baverman** [comment]
> windows XP

I have no any windows box around so can not test but I try to write more or less crossplatform code and appropriate fixes should be elementary enough.

Again, windows support will be after Snaked's stabilization. I think it's a matter of two-three months.

**Comment by bibile** [comment]
ok, no problem.
better to get something working perfectly under linux.

**Comment by baverman** [comment]
Solved
