### ISSUE TITLE
Ipython prevents plugins window to show

### ISSUE THREAD

**Issue by fdev31** [baverman/snaked#31]
When I try to access Plugins from Preferences:

<pre>
 Traceback (most recent call last):                                                                                               
  File "/home/fab/progs/snaked/snaked/core/gui/prefs.py", line 48, in activate
    prefs.registered_dialogs[name][1](self.editor())
  File "/home/fab/progs/snaked/snaked/core/plugins.py", line 213, in show_plugins_prefs
    dialog.show(self.enabled_plugins, set_plugin_list)
  File "/home/fab/progs/snaked/snaked/core/gui/plugin_prefs.py", line 32, in show
    self.fill_plugin_list(enabled_plugins)
  File "/home/fab/progs/snaked/snaked/core/gui/plugin_prefs.py", line 57, in fill_plugin_list
    for p in sorted(self.get_aviable_plugins(), key=lambda r: r[-1]):
  File "/home/fab/progs/snaked/snaked/core/gui/plugin_prefs.py", line 46, in get_aviable_plugins
    package = get_plugin(pname)
  File "/home/fab/progs/snaked/snaked/core/plugins.py", line 21, in get_plugin
    return get_package(package_name)
  File "/home/fab/progs/snaked/snaked/core/plugins.py", line 16, in get_package
    __import__(name)
  File "/home/fab/progs/snaked/snaked/plugins/python_ipython/__init__.py", line 6, in <module>
    from ipython_view import IPythonView
  File "/home/fab/progs/snaked/snaked/plugins/python_ipython/ipython_view.py", line 27, in <module>
    raise "Error importing IPython (%s)" % str(e)
TypeError: exceptions must be old-style classes or derived from BaseException, not str
</pre>

**Comment by bigdrum** [comment]
I suggest add a error handling routine at core.plugins.get_package. Also when user tries to enable the plugin, it would be nice to popup a message box indicating the cause of the importing error in a friendly way.

**Comment by fdev31** [comment]
Nothing related, but I'm rather new to github, is there some way to "publicly chat" about something ? I think it could be fine to open some discussions about next features/improvements ... like this one :)

**Comment by bigdrum** [comment]
@fdev31 If you mean realtime chat, I don't think so. IMHO, discussion in an issue ticket looks good since ppl might not be online at same time, and it is also a better way to keep everything in record.

**Comment by baverman** [comment]
I did quick fix to pass exception. Later I will show cause which prevents plugin from loading.
