### ISSUE TITLE
Clicking a checkbox in editor settings shows traceback

### ISSUE THREAD

**Issue by fdev31** [baverman/snaked#32]
If I check something like "language" in editor settings, the console displays:

<pre>

Traceback (most recent call last):
  File "/home/fab/progs/snaked/snaked/core/manager.py", line 230, in on_editor_settings_changed
    self.set_editor_prefs(editor, editor.uri, editor.contexts)
  File "/home/fab/progs/snaked/snaked/core/manager.py", line 143, in set_editor_prefs
    lang = self.lang_manager.get_language(lang_id)
TypeError: GtkSourceView.LanguageManager.get_language() argument 1 must be string, not list
</pre>

**Comment by baverman** [comment]
Fixed.
