### ISSUE TITLE
Error with bind_menu

### ISSUE THREAD

**Issue by yescalona** [baverman/snaked#53]
Im using snaked on Archlinux and I get this error 

bash$ snaked file
Traceback (most recent call last):
  File "/usr/bin/snaked", line 5, in <module>
    run()
  File "/usr/lib/python2.7/site-packages/snaked/core/run.py", line 45, in run
    manager = get_manager()
  File "/usr/lib/python2.7/site-packages/snaked/core/run.py", line 29, in get_manager
    manager = EditorManager(options.session)
  File "/usr/lib/python2.7/site-packages/snaked/core/manager.py", line 75, in **init**
    self.activator.bind_menu('_File#1')
TypeError: bind_menu() takes exactly 6 arguments (2 given)

**Comment by yescalona** [comment]
I dont have the uxie package "python2-uxie-git"
Now I can run snaked
