### ISSUE TITLE
Stale pop-up

### ISSUE THREAD

**Issue by fdev31** [baverman/snaked#55]
Given you have a /tmp/ folder with _NO_ file starting with the letter "w".

Trigger the shortcut to create a "New" file.
Clear the input text and type "/tmp/" => You get a big pop-up with all choices.
Now type "w" so the popup remains but with an empty content since there is no match anymore.
Type "ENTER" to validate the file name.

Expected: the popup disappear Got: the popup remains on screen until snaked is closed.

**Comment by baverman** [comment]
> Now type "w" so the popup remains but with an empty content since there is no match anymore.

Can't reproduce. Popup disappears. Can you provide an output of "ls -la /tmp"?

**Comment by fdev31** [comment]
Yup:

```

total 103584
-rw------- 1 fab31 fab31    8213 2012-02-15 10:50 debug.py~base.K0pRHR
-rw------- 1 fab31 fab31    9489 2012-02-15 10:50 debug.py~other.0Oc0od
-rw-r--r-- 1 fab31 fab31   10213 2012-02-14 09:39 detail?name=PyScripter-v2.4.3.zip
-r-------- 1 fab31 fab31   29826 2012-02-15 15:47 DT_ALTEN_CT.docx
-rw-r--r-- 1 fab31 fab31    2312 2012-02-15 10:58 f.bak
-r-------- 1 fab31 fab31   21274 2012-02-15 15:44 Formulaire évaluation promo 2015.docx
drwx------ 2 fab31 fab31      24 2012-02-13 09:25 keyring-1VHtdE
srwxrwxrwx 1 root  root        0 2012-02-13 09:24 mongodb-27017.sock
drwx------ 2 fab31 fab31    4096 2012-02-15 17:36 orbit-fab31
drwx------ 2 gdm   gdm        64 2012-02-13 09:25 orbit-gdm
drwx------ 2 root  root        1 2012-02-15 09:25 orbit-root
srwxr-xr-x 1 fab31 fab31       0 2012-02-15 15:44 OSL_PIPE_1001_SingleOfficeIPC_614e81662b3b5930e14e569b385ba
drwx------ 2 gdm   gdm         1 2012-02-13 09:25 pulse-PKdhtXMmr18n
drwx------ 2 fab31 fab31      32 2012-02-13 09:25 pulse-sRwpC5iUzahE
drwx------ 2 fab31 fab31       8 2012-02-15 10:59 pymp-Jc9v3U
drwx------ 3 fab31 fab31       8 2012-02-14 09:40 PyScripter-v2.4.3
-rw-r--r-- 1 fab31 fab31 5218543 2011-09-21 01:20 PyScripter-v2.4.3.zip
srwxr-xr-x 1 fab31 fab31       0 2012-02-15 10:59 snaked.session.1001.default
drwx------ 2 fab31 fab31       8 2012-02-13 09:25 ssh-BGdnNx1813
drwx------ 3 fab31 fab31       8 2012-02-14 09:30 Sublime Text 2 Build 2165
-rw-r--r-- 1 fab31 fab31 5637229 2012-01-12 06:36 Sublime Text 2 Build 2165.tar.bz2
drwxr-xr-x 2 fab31 fab31    4096 2012-02-15 15:48 sv8hn.tmp
-rw-r--r-- 1 fab31 fab31     404 2012-02-13 17:41 tst.py
srw-rw-rw- 1 fab31 fab31       0 2012-02-15 16:03 uwsgi.sock
drwx------ 2 fab31 fab31       1 2012-02-13 17:08 v1iHK4D
drwx------ 2 fab31 fab31       1 2012-02-15 16:37 vhD1cIN
-rw-r--r-- 1 fab31 fab31 5055344 2012-02-13 11:57 zsong.03b5974c9d6f625670566be65d2bcc28.mp3
-rw-r--r-- 1 fab31 fab31 2008380 2012-02-13 11:52 zsong.065da66a99b1c1df1dcf1d70616ca139.mp3
-rw-r--r-- 1 fab31 fab31 4366464 2012-02-13 11:43 zsong.1e317b6bb4ee91609fed05774d60c527.mp3
-rw-r--r-- 1 fab31 fab31 6401780 2012-02-13 18:59 zsong.3a97a95baa1e05b0b414e9c72138d725.mp3
-rw-r--r-- 1 fab31 fab31 5565068 2012-02-13 18:42 zsong.40ab8531a19661d34eaeb686ac7a2ff7.mp3
-rw-r--r-- 1 fab31 fab31 4748409 2012-02-13 19:01 zsong.42e39957f05931180a574416a41e0a93.ogg
-rw-r--r-- 1 fab31 fab31 1967069 2012-02-15 18:14 zsong.5e9dc5ce82bcf9418c4620b1e01e9766.mp3
-rw-r--r-- 1 fab31 fab31 6922512 2012-02-13 18:47 zsong.64f181a37c80c670969a6afe04f6593d.mpc
-rw-r--r-- 1 fab31 fab31 7692963 2012-02-13 11:48 zsong.699f0d46818ec407bafd0a18eabfde17.mp3
-rw-r--r-- 1 fab31 fab31 7452672 2012-02-13 11:41 zsong.8f7d2add37bd26046369e2bce27a213c.mp3
-rw-r--r-- 1 fab31 fab31 2369664 2012-02-13 18:54 zsong.adac1f32f60406d5674e8eaba446665c.mp3
-rw-r--r-- 1 fab31 fab31 5518287 2012-02-13 11:58 zsong.b05ac8c4c290f97b2ce617db8a0040b5.mp3
-rw-r--r-- 1 fab31 fab31 4980070 2012-02-15 18:18 zsong.b1dfb301733d2e7f11f5f282c8147fb5.mp3
-rw-r--r-- 1 fab31 fab31 7573599 2012-02-15 18:30 zsong.b51c5b38bee5393ad5f5c9b087b39e58.mp3
-rw-r--r-- 1 fab31 fab31 5470464 2012-02-13 12:03 zsong.ba0e4d911bf86bf8dea898e741fbdeaf.mp3
-rw-r--r-- 1 fab31 fab31 4620416 2012-02-13 18:50 zsong.e7c4b717e8e4fbfdc2e7955aba99fa4d.mp3
-rw-r--r-- 1 fab31 fab31 5610517 2012-02-15 18:16 zsong.ecbadf719f97e09023204fc91771df8e.mp3
-rw-r--r-- 1 fab31 fab31 4177588 2012-02-15 18:22 zsong.f8b372d2b9108bc0c3b829254f816086.mp3
-rw-r--r-- 1 fab31 fab31 2467840 2012-02-15 18:26 zsong.fa6adca979ef4705d5da2ac337b47090.mp3
```

**Comment by baverman** [comment]
No luck. Still can't reproduce. I tried to create sockets and entries with restricted permissions but completion widget works fine. Is there any messages in stdout?

**Comment by fdev31** [comment]
Ooops, I didn't noticed that...

When I press "backspace" to set the filename from "/tmp/w" to "/tmp/" I get this uxie exception:

```
Traceback (most recent call last):
  File "/home/fab31/progs/uxie/uxie/utils.py", line 12, in idle_callback
    callable(*args, **kwargs)
  File "/home/fab31/progs/uxie/uxie/complete.py", line 40, in request_fill
    self.popup(widget)
  File "/home/fab31/progs/uxie/uxie/complete.py", line 86, in popup
    send_focus_change(self.view, True)
  File "/home/fab31/progs/uxie/uxie/utils.py", line 50, in send_focus_change
    widget.send_focus_change(event)
AttributeError: 'gtk.TreeView' object has no attribute 'send_focus_change'
```

Then, if I type "w" again I get another one:

```
Traceback (most recent call last):
  File "/home/fab31/progs/uxie/uxie/utils.py", line 12, in idle_callback
    callable(*args, **kwargs)
  File "/home/fab31/progs/uxie/uxie/complete.py", line 47, in request_fill
    self.popdown(widget)
  File "/home/fab31/progs/uxie/uxie/complete.py", line 107, in popdown
    widget.handler_disconnect(self.key_press_handler_id)
AttributeError: 'EntryCompleter' object has no attribute 'key_press_handler_id'
```

I hope it helps better...

**Comment by baverman** [comment]
> AttributeError: 'gtk.TreeView' object has no attribute 'send_focus_change'

Oh, you need pygtk 2.22 at least.
