### ISSUE TITLE
error with bind_accel

### ISSUE THREAD

**Issue by yescalona** [baverman/snaked#58]
i have this error when start snaked
i use python2-uxie-git

$ snaked

*\* (process:24380): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

*\* (process:24380): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

*\* (process:24380): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/snaked/core/plugins.py", line 31, in init_plugin
    p = get_plugin(name)
  File "/usr/lib/python2.7/site-packages/snaked/core/plugins.py", line 27, in get_plugin
    return get_package(package_name)
  File "/usr/lib/python2.7/site-packages/snaked/core/plugins.py", line 22, in get_package
    **import**(name)
ImportError: No module named python_flakes
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/uxie/plugins.py", line 53, in add_plugin
    plugin.init(self.injector)
  File "/usr/lib/python2.7/site-packages/snaked/plugins/goto_dir/**init**.py", line 6, in init
    injector.bind_accel('editor-active', 'goto-dir', 'File/Open file\'s directory#30',
AttributeError: 'Injector' object has no attribute 'bind_accel'

i dont know what to do
Thanks in advance
Regards

**Comment by baverman** [comment]
Oh, forgot about deprecated goto_dir plugin. You can simply disable it in plugin settings.
